"""
Build script to create executable using PyInstaller
"""

import PyInstaller.__main__
import os
import sys
import shutil

def build_executable():
    """Build the executable using PyInstaller"""
    
    # PyInstaller arguments
    args = [
        'main.py',
        '--name=GameBoostPro',
        '--windowed',  # No console window
        '--onefile',   # Single executable file
        '--icon=assets/icon.ico',
        '--add-data=assets;assets',
        '--add-data=src;src',
        '--hidden-import=psutil',
        '--hidden-import=customtkinter',
        '--hidden-import=matplotlib',
        '--hidden-import=numpy',
        '--hidden-import=win32api',
        '--hidden-import=win32con',
        '--hidden-import=win32process',
        '--hidden-import=win32gui',
        '--hidden-import=wmi',
        '--hidden-import=GPUtil',
        '--clean',
        '--noconfirm'
    ]
    
    # Add version info for Windows
    if os.name == 'nt':
        version_file = create_version_file()
        if version_file:
            args.extend(['--version-file', version_file])
    
    print("Building executable with PyInstaller...")
    print(f"Arguments: {' '.join(args)}")
    
    try:
        PyInstaller.__main__.run(args)
        print("\nBuild completed successfully!")
        print("Executable location: dist/GameBoostPro.exe")
        
        # Clean up build artifacts
        cleanup_build()
        
    except Exception as e:
        print(f"Build failed: {e}")
        return False
        
    return True

def create_version_file():
    """Create version file for Windows executable"""
    version_info = """
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(1, 0, 0, 0),
    prodvers=(1, 0, 0, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'GameBoost Pro'),
           StringStruct(u'FileDescription', u'Advanced System Monitor and Gaming Optimizer'),
           StringStruct(u'FileVersion', u'1.0.0.0'),
           StringStruct(u'InternalName', u'GameBoostPro'),
           StringStruct(u'LegalCopyright', u'Copyright © 2025 GameBoost Pro'),
           StringStruct(u'OriginalFilename', u'GameBoostPro.exe'),
           StringStruct(u'ProductName', u'GameBoost Pro'),
           StringStruct(u'ProductVersion', u'1.0.0.0')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    
    try:
        with open('version_info.txt', 'w') as f:
            f.write(version_info)
        return 'version_info.txt'
    except:
        return None

def cleanup_build():
    """Clean up build artifacts"""
    try:
        # Remove build directory
        if os.path.exists('build'):
            shutil.rmtree('build')
            
        # Remove spec file
        if os.path.exists('GameBoostPro.spec'):
            os.remove('GameBoostPro.spec')
            
        # Remove version file
        if os.path.exists('version_info.txt'):
            os.remove('version_info.txt')
            
        print("Build artifacts cleaned up.")
        
    except Exception as e:
        print(f"Warning: Could not clean up build artifacts: {e}")

def create_installer():
    """Create NSIS installer script"""
    installer_script = """
; GameBoost Pro Installer Script
; Generated by build script

!define APPNAME "GameBoost Pro"
!define COMPANYNAME "GameBoost Pro Team"
!define DESCRIPTION "Advanced System Monitor and Gaming Optimizer"
!define VERSIONMAJOR 1
!define VERSIONMINOR 0
!define VERSIONBUILD 0
!define HELPURL "https://github.com/gameboostpro/gameboostpro"
!define UPDATEURL "https://github.com/gameboostpro/gameboostpro/releases"
!define ABOUTURL "https://github.com/gameboostpro/gameboostpro"
!define INSTALLSIZE 50000

RequestExecutionLevel admin
InstallDir "$PROGRAMFILES\\${COMPANYNAME}\\${APPNAME}"
Name "${APPNAME}"
Icon "assets\\icon.ico"
outFile "GameBoostPro_Setup.exe"

!include LogicLib.nsh

page components
page directory
page instfiles

!macro VerifyUserIsAdmin
UserInfo::GetAccountType
pop $0
${If} $0 != "admin"
    messageBox mb_iconstop "Administrator rights required!"
    setErrorLevel 740
    quit
${EndIf}
!macroend

function .onInit
    setShellVarContext all
    !insertmacro VerifyUserIsAdmin
functionEnd

section "install"
    setOutPath $INSTDIR
    file "dist\\GameBoostPro.exe"
    file /r "assets"
    
    writeUninstaller "$INSTDIR\\uninstall.exe"
    
    createDirectory "$SMPROGRAMS\\${COMPANYNAME}"
    createShortCut "$SMPROGRAMS\\${COMPANYNAME}\\${APPNAME}.lnk" "$INSTDIR\\GameBoostPro.exe" "" "$INSTDIR\\assets\\icon.ico"
    createShortCut "$DESKTOP\\${APPNAME}.lnk" "$INSTDIR\\GameBoostPro.exe" "" "$INSTDIR\\assets\\icon.ico"
    
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "DisplayName" "${APPNAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "UninstallString" "$\\"$INSTDIR\\uninstall.exe$\\""
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "QuietUninstallString" "$\\"$INSTDIR\\uninstall.exe$\\" /S"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "InstallLocation" "$\\"$INSTDIR$\\""
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "DisplayIcon" "$\\"$INSTDIR\\assets\\icon.ico$\\""
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "Publisher" "${COMPANYNAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "HelpLink" "${HELPURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "URLUpdateInfo" "${UPDATEURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "URLInfoAbout" "${ABOUTURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "DisplayVersion" "${VERSIONMAJOR}.${VERSIONMINOR}.${VERSIONBUILD}"
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "VersionMajor" ${VERSIONMAJOR}
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "VersionMinor" ${VERSIONMINOR}
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "NoModify" 1
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "NoRepair" 1
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}" "EstimatedSize" ${INSTALLSIZE}
sectionEnd

section "uninstall"
    delete "$INSTDIR\\GameBoostPro.exe"
    delete "$INSTDIR\\uninstall.exe"
    rmDir /r "$INSTDIR\\assets"
    rmDir "$INSTDIR"
    
    delete "$SMPROGRAMS\\${COMPANYNAME}\\${APPNAME}.lnk"
    rmDir "$SMPROGRAMS\\${COMPANYNAME}"
    delete "$DESKTOP\\${APPNAME}.lnk"
    
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${COMPANYNAME} ${APPNAME}"
sectionEnd
"""
    
    try:
        with open('installer.nsi', 'w') as f:
            f.write(installer_script)
        print("Installer script created: installer.nsi")
        print("Use NSIS to compile the installer.")
        return True
    except Exception as e:
        print(f"Error creating installer script: {e}")
        return False

if __name__ == "__main__":
    print("GameBoost Pro Build Script")
    print("=" * 40)
    
    # Check if assets directory exists
    if not os.path.exists('assets'):
        os.makedirs('assets')
        print("Created assets directory")
    
    # Build executable
    if build_executable():
        print("\n" + "=" * 40)
        print("Build Summary:")
        print("✓ Executable created successfully")
        print("✓ Build artifacts cleaned up")
        
        # Create installer script
        if create_installer():
            print("✓ Installer script created")
            
        print("\nNext steps:")
        print("1. Test the executable: dist/GameBoostPro.exe")
        print("2. Compile installer with NSIS (optional)")
        print("3. Distribute the application")
        
    else:
        print("Build failed!")
        sys.exit(1)